<?php
// Ranged attack modifcation calculator

function fernkampf_mod(int $distance,
    $size,
    $protection,
    $movement,
    $sight,
    $adv1,
    $adv2,
    $adv3,
    $disadv1, 
    $disadv2,
    $disadv3,
    $disadv4,
    $other1,
    $other2,
    $other3,
    $other4,
    $other5,
    $other6,
    $other7,
    $other8,
    $other9,
    $other10,
    $other11,
    ) {
        echo "$distance, $size,
        $protection,
        $movement,
        $sight,
        $adv1,
        $adv2,
        $adv3,
        $disadv1, 
        $disadv2,
        $disadv3,
        $disadv4,
        $other1,
        $other2,
        $other3,
        $other4,
        $other5,
        $other6,
        $other7,
        $other8,
        $other9,
        $other10,
        $other11";
}
?> 